{% set name = "sphericart" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/lab-cosmo/sphericart/archive/v{{ version }}.tar.gz
    sha256: 8d1da0f9ddadd285214bd0a6c0343f13a758ebf189212ec1448ab5255b575b16

build:
  number: 1
  skip: true  # [cuda_compiler_version != "None" and ppc64le]
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - libgomp      # [not osx]
    - llvm-openmp
    - make
    - ninja
    - pip         # [build_platform != target_platform]
    - pybind11    # [build_platform != target_platform]
    - python      # [build_platform != target_platform]
    - setuptools  # [build_platform != target_platform]
    {% if cuda_compiler_version != "None" %}
    - {{ compiler("cuda") }}
    - cuda-nvcc
    - cuda-toolkit
    {% endif %}
  host:
    - libgomp      # [not osx]
    - llvm-openmp
    - pip
    - python
    - setuptools
    {% if cuda_compiler_version != "None" %}
    - {{ compiler("cuda") }}
    - cuda-nvcc
    - cuda-toolkit
    {% endif %}
  run:
    - numpy
    - python

test:
  imports:
    - sphericart
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: sphericart
  - name: sphericart-torch
    script: build_torch.sh  # [unix]
    build:
      skip: true  # [ppc64le]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - cmake
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - libgomp      # [not osx]
        - llvm-openmp
        - make
        - ninja
        - pip         # [build_platform != target_platform]
        - pybind11    # [build_platform != target_platform]
        - python      # [build_platform != target_platform]
        - pytorch     # [build_platform != target_platform]
        - setuptools  # [build_platform != target_platform]
        {% if cuda_compiler_version != "None" %}
        - {{ compiler("cuda") }}
        - cuda-nvcc
        - cuda-toolkit
        {% endif %}
      host:
        - libgomp      # [not osx]
        - llvm-openmp
        - pip
        - python
        - pytorch
        - setuptools
        {% if cuda_compiler_version != "None" %}
        - cuda-version {{ cuda_compiler_version }}
        - cuda-nvcc
        - cuda-toolkit
        {% endif %}
      run:
        - {{ pin_subpackage("sphericart", exact=True) }}
        - numpy
        - python
        - pytorch
    test:
      imports:
        - sphericart.torch  # [cuda_compiler_version != "None"]
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/lab-cosmo/sphericart
  summary: Multi-language library for the calculation of spherical harmonics in Cartesian coordinates
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jeongseok-meta
