{% set name = "sphericart" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphericart-{{ version }}.tar.gz
    sha256: e5790e33c10460a84538ba3088b02fc5142a8af32a0c697bbad290f26f09093b

build:
  number: 1
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [win]

outputs:
  - name: sphericart
    script: build.sh  # [unix]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
        - cmake
        - cuda-nvcc
        - cuda-toolkit
        - libgomp
        - llvm-openmp
        - make
        - ninja
        - pip         # [build_platform != target_platform]
        - pybind11    # [build_platform != target_platform]
        - python      # [build_platform != target_platform]
        - pytorch     # [build_platform != target_platform]
        - setuptools  # [build_platform != target_platform]
      host:
        - cuda-version {{ cuda_compiler_version }}
        - cuda-nvcc
        - cuda-toolkit
        - libgomp
        - llvm-openmp
        - pip
        - python
        - pytorch
        - setuptools
      run:
        - numpy
        - python
        - pytorch
    test:
      imports:
        - sphericart
      commands:
        - pip check
      requires:
        - pip

  - name: sphericart-torch
    script: build_torch.sh  # [unix]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
        - cmake
        - cuda-nvcc
        - cuda-toolkit
        - libgomp
        - llvm-openmp
        - make
        - ninja
        - pip         # [build_platform != target_platform]
        - pybind11    # [build_platform != target_platform]
        - python      # [build_platform != target_platform]
        - pytorch     # [build_platform != target_platform]
        - setuptools  # [build_platform != target_platform]
      host:
        - cuda-version {{ cuda_compiler_version }}
        - cuda-nvcc
        - cuda-toolkit
        - libgomp
        - llvm-openmp
        - pip
        - python
        - pytorch
        - setuptools
      run:
        - {{ pin_subpackage("sphericart", exact=True) }}
        - numpy
        - python
        - pytorch
    test:
      imports:
        - sphericart.torch  # [cuda_compiler_version != "None"]
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/lab-cosmo/sphericart
  summary: Multi-language library for the calculation of spherical harmonics in Cartesian coordinates
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jeongseok-meta
